server:
  port: 8082

spring:
  application:
    name: mall
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root123456


mybatis:
  mapper-locations:
    - classpath*:com.zgq.mall.mapper/*.xml